name: CI

# Variables
env:
  IP_ROOT: ./test/designs/.ip-root
# Events that trigger workflow
on:
  # Runs on all pushes to branches
  push:

jobs:
  test:
    name: Try Lima
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install and Start Lima
        run: |
          brew install lima
      - name: Create Lima VM
        run: |
          limactl create --name=default $PWD/lima.tpl
      - name: Start Lima?
        run: |
          limactl start
